"""Dendrite config builder — extracted from retired provision_templates (#SEC5/#99).

Used by provision/netconfig.py claim-time regen and any provisioner that needs a
matrix.{domain} homeserver config. Kept under provision/ (not src/) so the CLI
path stays free of dashboard imports.
"""

# rooms. Federation connects homeservers across DIFFERENT machines.
#
# This builder templatizes the previously hand-maintained Services/Dendrite/
# dendrite.yaml: server_name from the family domain, real secrets, and the
# rate-limit bot exemptions derived from the family's agent ids.

def build_dendrite_config(*, server_name: str, db_password: str,
                          registration_shared_secret: str,
                          bot_user_ids=None) -> str:
    """Generate dendrite.yaml for a machine's Matrix homeserver.

    server_name: e.g. 'matrix.cove.lucidcove.org' (matrix.{family_domain}).
    db_password: real generated Postgres password (must match the .env).
    registration_shared_secret: generated; gates account creation.
    bot_user_ids: agent localparts exempt from client-API rate limiting
        (e.g. ['stuart', 'atlas', 'lt']) -> '@stuart:{server_name}' etc.
    """
    bots = list(bot_user_ids or [])
    if bots:
        exempt_block = "    exempt_user_ids:\n" + "\n".join(
            f'      - "@{b}:{server_name}"' for b in bots)
    else:
        exempt_block = "    exempt_user_ids: []"

    return f"""\
# =============================================================================
# Dendrite Configuration — Lucid Cove Matrix Homeserver
# =============================================================================
# Generated by the provisioner (#127). One homeserver per machine.
# Domain: {server_name}
# =============================================================================

version: 2

global:
  server_name: {server_name}
  private_key: /etc/dendrite/matrix_key.pem
  key_validity_period: 168h0m0s

  database:
    connection_string: postgresql://dendrite:{db_password}@postgres:5432/dendrite?sslmode=disable
    max_open_conns: 90
    max_idle_conns: 5
    conn_max_lifetime: -1

  cache:
    max_size_estimated: 1073741824  # 1GB
    max_age: 1h

  jetstream:
    storage_path: /var/dendrite/jetstream
    in_memory: false
    topic_prefix: Dendrite

  metrics:
    enabled: false

  dns_cache:
    enabled: true
    cache_size: 256
    cache_lifetime: 5m

client_api:
  registration_disabled: true
  registration_shared_secret: "{registration_shared_secret}"
  # Rate limiting — relaxed for internal use
  rate_limiting:
    enabled: true
    threshold: 20
    cooloff_ms: 500
{exempt_block}

federation_api:
  send_max_retries: 16
  disable_tls_validation: false
  prefer_direct_fetch: false
  disable_http_keepalives: false
  # Federation SSRF allowlist (#132). Dendrite's default deny_networks includes
  # 100.64.0.0/10 (the Tailscale/Headscale CGNAT range), which BLOCKS federation
  # to mesh IPs and breaks Cove<->Cove / hub<->Cove federation over the mesh.
  # We drop 100.64.0.0/10 from the deny list so mesh federation works, while
  # keeping every other private range blocked for SSRF safety.
  deny_networks:
  - 127.0.0.1/8
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - ::1/128
  - fe80::/64
  - fc00::/7
  allow_networks:
  - 0.0.0.0/0
  key_perspectives:
    - server_name: matrix.org
      keys:
        - key_id: ed25519:auto
          public_key: Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw

media_api:
  base_path: /var/dendrite/media
  max_file_size_bytes: 10485760  # 10MB
  dynamic_thumbnails: false
  max_thumbnail_generators: 10
  thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 640
      height: 480
      method: scale

sync_api:
  search:
    enabled: true
    index_path: /var/dendrite/searchindex
    language: en

user_api:
  auto_join_rooms: []

mscs:
  mscs: []

logging:
  - type: std
    level: info
"""
